apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobs-service-deployment
  labels:
    app: blobs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blobs-service
  template:
    metadata:
      labels:
        app: blobs-service
    spec:
      containers:
        - name: blobs-service
          image: guipma/blobs-service-70231:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: blobs-storage
              mountPath: /data
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: blobs-service-config
                  key: spring.profiles.active
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
      volumes:
        - name: blobs-storage
          persistentVolumeClaim:
            claimName: blobs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: blobs-service
spec:
  selector:
    app: blobs-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30070
  type: LoadBalancer