apiVersion: v1
kind: PersistentVolume
metadata:
  name: blobs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Matches PVC's storage class
  hostPath:
    path: /mnt/data/blobs-service  # Directory on the node